import { ApiProperty } from '@nestjs/swagger';
import { ProviderType } from '@prisma/client';

export class TokenUsageDto {
  @ApiProperty({ example: 15, description: 'Tokens estimated for the prompt input' })
  prompt: number;

  @ApiProperty({ example: 48, description: 'Tokens generated in completion output' })
  completion: number;

  @ApiProperty({ example: 63, description: 'Total tokens consumed' })
  total: number;
}

export class SendPromptResponseDto {
  @ApiProperty({ example: 'a1b2c3d4-e5f6-7890-abcd-ef1234567890' })
  conversationId: string;

  @ApiProperty({ example: 'b2c3d4e5-f6a7-8901-bcde-f12345678901' })
  messageId: string;

  @ApiProperty({
    example: 'TypeScript provides static type analysis which helps catch runtime errors during development...',
    description: 'Assistant completion text generated by the AI model',
  })
  response: string;

  @ApiProperty({ enum: ProviderType, example: ProviderType.GEMINI })
  provider: ProviderType;

  @ApiProperty({ example: 'gemini-1.5-flash' })
  modelUsed: string;

  @ApiProperty({ type: TokenUsageDto })
  tokensUsed: TokenUsageDto;

  @ApiProperty({ example: '2026-09-29T12:00:00.000Z' })
  createdAt: Date;
}
