import { Injectable, Logger } from '@nestjs/common';
import { ProviderType } from '@prisma/client';
import { AiProviderAdapter } from './ai-provider-adapter.interface';
import { AiResponse, ChatMessageContext } from './ai-response.interface';

@Injectable()
export class GeminiAdapter implements AiProviderAdapter {
  readonly providerType = ProviderType.GEMINI;
  private readonly logger = new Logger(GeminiAdapter.name);

  async generateCompletion(
    prompt: string,
    model: string,
    apiKey: string,
    baseUrl?: string | null,
    history?: ChatMessageContext[],
  ): Promise<AiResponse> {
    const isMock =
      !apiKey ||
      apiKey.startsWith('mock') ||
      apiKey.startsWith('AIzaSyDemo') ||
      process.env.NODE_ENV === 'test';

    if (isMock) {
      const mockText = `[Gemini ${model}] Here is a helpful response regarding: "${prompt}". TypeScript and modern web architectures provide robust typing and scalable full-stack capabilities.`;
      const promptTokens = Math.ceil(prompt.length / 4);
      const completionTokens = Math.ceil(mockText.length / 4);

      return {
        text: mockText,
        promptTokens,
        completionTokens,
        totalTokens: promptTokens + completionTokens,
        model,
      };
    }

    const host = baseUrl || 'https://generativelanguage.googleapis.com';
    const url = `${host}/v1beta/models/${model}:generateContent?key=${apiKey}`;

    const contents: any[] = [];
    if (history && history.length > 0) {
      for (const msg of history) {
        contents.push({
          role: msg.role === 'USER' ? 'user' : 'model',
          parts: [{ text: msg.content }],
        });
      }
    }
    contents.push({
      role: 'user',
      parts: [{ text: prompt }],
    });

    const response = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ contents }),
    });

    if (!response.ok) {
      const errText = await response.text();
      this.logger.error(`Gemini API error: ${response.status} - ${errText}`);
      throw new Error(`Google Gemini API error: ${response.statusText}`);
    }

    const data = await response.json();
    const text =
      data.candidates?.[0]?.content?.parts?.[0]?.text ||
      'No response generated by Gemini model.';
    const promptTokens =
      data.usageMetadata?.promptTokenCount || Math.ceil(prompt.length / 4);
    const completionTokens =
      data.usageMetadata?.candidatesTokenCount || Math.ceil(text.length / 4);

    return {
      text,
      promptTokens,
      completionTokens,
      totalTokens: promptTokens + completionTokens,
      model,
    };
  }
}
